[package]
name = "paradigmextract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
eyre = "0.6.12"
nanoserde = "0.1.37"
